filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

# see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
build:
  dependencies:
    before:
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=$HOME/bin --filename=composer
      - php -r "unlink('composer-setup.php');"
      - $HOME/bin/composer --version
    override:
      - composer update --no-interaction
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
  external_code_coverage: true
