#!/bin/bash -e

cd "$(dirname "$0")"

PHAR_BUILDER_LOCATION="https://github.com/MacFJA/PharBuilder/releases/download/0.2.8/phar-builder.phar"
PHAR_BUILDER_BIN="tools/phar-builder"

if [ ! -e "$PHAR_BUILDER_BIN" ]; then
    mkdir -p "$(dirname "$PHAR_BUILDER_BIN")"
    wget -O "$PHAR_BUILDER_BIN" "$PHAR_BUILDER_LOCATION"
fi

git describe --tags > bin/version.txt
rm -f build/cfditopdf.phar
php -dphar.readonly=0 tools/phar-builder package --no-interaction
rm bin/version.txt
