#!/bin/bash -e

PHAR_BUILDER_LOCATION="https://github.com/MacFJA/PharBuilder/releases/latest/download/phar-builder.phar"
PHAR_BUILDER_BIN="build/phar-builder"

# this is set in composer.json
PHAR_DESTINATION="build/cfditopdf.phar"

if [ ! -e "$PHAR_BUILDER_BIN" ]; then
    mkdir -p "$(dirname "$PHAR_BUILDER_BIN")"
    wget -O "$PHAR_BUILDER_BIN" "$PHAR_BUILDER_LOCATION"
fi

git describe --tags > bin/version.txt
mkdir -p "$(dirname "$PHAR_DESTINATION")"
rm -f "$PHAR_DESTINATION"
php -d phar.readonly=0 build/phar-builder package --no-interaction
rm bin/version.txt
