#!/usr/bin/env php
<?php

declare(strict_types=1);

exit(call_user_func(function () {
    try {
        $source = 'https://api.github.com/repos/MacFJA/PharBuilder/releases/latest';

        $context = stream_context_create([
            'http' => [
                'protocol_version' => '1.1',
                'header' => ['User-Agent: PHP']
            ],
        ]);
        $content = (string) file_get_contents($source, false, $context);
        if ('' === $content) {
            throw new \RuntimeException("Invalid content from $source");
        }

        $json = json_decode($content, true);
        if (null === $json) {
            throw new \RuntimeException("Cannot decode content from $source");
        }

        $assets = $json['assets'] ?? [];
        $urlToDownload = '';
        foreach ($assets as $asset) {
            $assetName = $asset['name'] ?? '';
            if ('phar-builder.phar' !== $assetName) {
                continue;
            }
            $urlToDownload = $asset['browser_download_url'] ?? '';
        }
        if ('' === $urlToDownload) {
            throw new \RuntimeException('Cannot find the asset from latest release');
        }

        $destination = __DIR__ . '/phar-builder.phar';
        if (! @copy($urlToDownload, $destination, $context)) {
            throw new \RuntimeException("Cannot copy from $source to $destination");
        }

        echo "Downloaded $source to $destination\n";
        return 0;
    } catch (\Throwable $exception) {
        // white/red message reset-color EOL
        $message = "\033[1;31m" . $exception->getMessage() . " \033[0m" . PHP_EOL;
        file_put_contents('php://stderr', $message, FILE_APPEND);

        return 1;
    }
}));
